# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2.1
notify:
  webhooks:
    - url: https://coveralls.io/webhook?repo_token=$COVERALLS_REPO_TOKEN
orbs:
  codecov: codecov/codecov@1.0.3
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:10.5

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    working_directory: ~/kyanite

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run:
          name: install-deps
          command: npm ci

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      # lint
      - run:
          name: lint
          command: npm run lint
      # run tests and report coverage
      - run:
          name: test
          command: npm run test:cov
      # generate coverage report
      - run:
          name: generate-report
          command: npm run report
      # send to codecov
      - codecov/upload:
          upload_name: k-tests
          file: coverage.lcov
      # run coverage check
      - run:
          name: coverage
          command: npm run check-cov
